name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.5
    - name: Build and Deploy
      uses: rreichel3/vuepress-github-actions-deploy@v3.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: docs/.vuepress/dist/
        BUILD_SCRIPT: yarn && yarn build
        PAGES_CNAME: cryb.d3sox.me
